// your JSON object
const data = {
   line_items: [
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X10184",
      "Quantity": "8",
      "Item_Description": "3X5 ACTIVE SCRAPER",
      "Unit_Of_Measure": "",
      "Unit_Price": "1.520",
      "Total_Line_Amount": "12.16",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X10184"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X1911",
      "Quantity": "4",
      "Item_Description": "3X5 WELLNESS AF BRN",
      "Unit_Of_Measure": "",
      "Unit_Price": "3.090",
      "Total_Line_Amount": "12.36",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X1911"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X2272",
      "Quantity": "32",
      "Item_Description": "FC4 NEUTRAL FLR CLNR-",
      "Unit_Of_Measure": "",
      "Unit_Price": "1.280",
      "Total_Line_Amount": "40.96",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X2272"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X7500",
      "Quantity": "1",
      "Item_Description": "CLEANING CHEM DISP-",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.000",
      "Total_Line_Amount": "0.00",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X7500"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X8004",
      "Quantity": "9",
      "Item_Description": "LAUNDRY LOCK UP-",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.410",
      "Total_Line_Amount": "3.69",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X8004"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X8010",
      "Quantity": "2",
      "Item_Description": "HANGER RACK-",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.000",
      "Total_Line_Amount": "0.00",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X8010"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X84035",
      "Quantity": "8",
      "Item_Description": "3X10 BLACK MAT",
      "Unit_Of_Measure": "",
      "Unit_Price": "3.050",
      "Total_Line_Amount": "24.40",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X84035"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X84335",
      "Quantity": "1",
      "Item_Description": "3X5 BLACK MAT",
      "Unit_Of_Measure": "",
      "Unit_Price": "1.520",
      "Total_Line_Amount": "1.52",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X84335"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X84435",
      "Quantity": "6",
      "Item_Description": "4X6 BLACK MAT",
      "Unit_Of_Measure": "",
      "Unit_Price": "2.440",
      "Total_Line_Amount": "14.64",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X84435"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X84501",
      "Quantity": "1",
      "Item_Description": "4X8 LOGO MAT 4X8 SCOTT'S",
      "Unit_Of_Measure": "",
      "Unit_Price": "4.880",
      "Total_Line_Amount": "4.88",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X84501"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X9210",
      "Quantity": "2",
      "Item_Description": "URINAL SCREEN SVC",
      "Unit_Of_Measure": "",
      "Unit_Price": "1.270",
      "Total_Line_Amount": "2.54",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X9210"
    },
    {
      "testfield1": "",
      "Sl_No": "",
      "Part_Number_SKU": "X9215",
      "Quantity": "2",
      "Item_Description": "URINAL SCREEN RFL-",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.000",
      "Total_Line_Amount": "0.00",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X9215"
    },
    {
      "testfield1": "",
      "Sl_No": "0001",
      "Part_Number_SKU": "X280",
      "Quantity": "11",
      "Item_Description": "FR JEAN/CARHART/RLX FIT/ DENIM-04030",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.570",
      "Total_Line_Amount": "6.27",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X280"
    },
    {
      "testfield1": "",
      "Sl_No": "0001",
      "Part_Number_SKU": "X59330",
      "Quantity": "11",
      "Item_Description": "SHIRT/W/RFLCT TRIM/CTN/NAVY/SS-RG0XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "4.18",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59330"
    },
    {
      "testfield1": "",
      "Sl_No": "0002",
      "Part_Number_SKU": "X59935",
      "Quantity": "5",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/LS-00MLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "1.80",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0002",
      "Part_Number_SKU": "X59935",
      "Quantity": "6",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/SS-RG00M",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "2.16",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0003",
      "Part_Number_SKU": "X59340",
      "Quantity": "11",
      "Item_Description": "PANT/COTTON/NAVY W/REFLCT TRIM-04430",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "4.18",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59340"
    },
    {
      "testfield1": "",
      "Sl_No": "0003",
      "Part_Number_SKU": "X59935",
      "Quantity": "11",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/SS-RG2XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "3.96",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0006",
      "Part_Number_SKU": "X59330",
      "Quantity": "5",
      "Item_Description": "SHIRT/W/RFLCT TRIM/CTN/NAVY/LS-3XLLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "1.90",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59330"
    },
    {
      "testfield1": "",
      "Sl_No": "0006",
      "Part_Number_SKU": "X59330",
      "Quantity": "6",
      "Item_Description": "SHIRT/W/RFLCT TRIM/CTN/NAVY/SS-RG3XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "2.28",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59330"
    },
    {
      "testfield1": "",
      "Sl_No": "0006",
      "Part_Number_SKU": "X59340",
      "Quantity": "11",
      "Item_Description": "PANT/COTTON/NAVY W/REFLCT TRIM-04034",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "4.18",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59340"
    },
    {
      "testfield1": "",
      "Sl_No": "0007",
      "Part_Number_SKU": "X280",
      "Quantity": "5",
      "Item_Description": "FR JEAN/CARHART/RLX FIT/ DENIM-03832",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.570",
      "Total_Line_Amount": "2.85",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X280"
    },
    {
      "testfield1": "",
      "Sl_No": "0007",
      "Part_Number_SKU": "X59340",
      "Quantity": "11",
      "Item_Description": "PANT/COTTON/NAVY W/REFLCT TRIM-03832",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "4.18",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59340"
    },
    {
      "testfield1": "",
      "Sl_No": "0007",
      "Part_Number_SKU": "X59935",
      "Quantity": "11",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/SS-RG0XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "3.96",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0008",
      "Part_Number_SKU": "X59340",
      "Quantity": "11",
      "Item_Description": "PANT/COTTON/NAVY W/REFLCT TRIM-03830",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "4.18",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59340"
    },
    {
      "testfield1": "",
      "Sl_No": "0008",
      "Part_Number_SKU": "X59935",
      "Quantity": "6",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/LS-0XLLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "2.16",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0008",
      "Part_Number_SKU": "X59935",
      "Quantity": "5",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/SS-RG0XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "1.80",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0009",
      "Part_Number_SKU": "X280",
      "Quantity": "11",
      "Item_Description": "FR JEAN/CARHART/RLX FIT/DENIM-03032",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.570",
      "Total_Line_Amount": "6.27",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X280"
    },
    {
      "testfield1": "",
      "Sl_No": "0009",
      "Part_Number_SKU": "X59330",
      "Quantity": "6",
      "Item_Description": "SHIRT/W/RFLCT TRIM/CTN/NAVY/LS-00MLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "2.28",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59330"
    },
    {
      "testfield1": "",
      "Sl_No": "0010",
      "Part_Number_SKU": "X59340",
      "Quantity": "11",
      "Item_Description": "PANT/COTTON/NAVY W/REFLCT TRIM-03430",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "4.18",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59340"
    },
    {
      "testfield1": "",
      "Sl_No": "0010",
      "Part_Number_SKU": "X59935",
      "Quantity": "6",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/LS-00LLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "2.16",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0010",
      "Part_Number_SKU": "X59935",
      "Quantity": "5",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/SS-RG00L",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "1.80",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0011",
      "Part_Number_SKU": "X382",
      "Quantity": "8",
      "Item_Description": "JEAN/CARHARTT CARPENTER/DENIM-03432",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.420",
      "Total_Line_Amount": "3.36",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X382"
    },
    {
      "testfield1": "",
      "Sl_No": "0011",
      "Part_Number_SKU": "X59945",
      "Quantity": "3",
      "Item_Description": "WRK PNT/NAVY/TWL/RFLT STRP-03432",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "1.08",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59945"
    },
    {
      "testfield1": "",
      "Sl_No": "0024",
      "Part_Number_SKU": "X59935",
      "Quantity": "5",
      "Item_Description": "UF SHR/NAVY/CMFT/RFT STR/SS-RG0XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "1.80",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59935"
    },
    {
      "testfield1": "",
      "Sl_No": "0024",
      "Part_Number_SKU": "X59945",
      "Quantity": "5",
      "Item_Description": "WRK PNT/NAVY/TWL/RFLT STRP-04230",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.360",
      "Total_Line_Amount": "1.80",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59945"
    },
    {
      "testfield1": "",
      "Sl_No": "0004",
      "Part_Number_SKU": "X280",
      "Quantity": "11",
      "Item_Description": "FR JEAN/CARHART/RLX FIT/ DENIM-03634",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.570",
      "Total_Line_Amount": "6.27",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X280"
    },
    {
      "testfield1": "",
      "Sl_No": "0004",
      "Part_Number_SKU": "X59330",
      "Quantity": "6",
      "Item_Description": "SHIRT/W/RFLCT TRIM/CTN/NAVY/SS-RG0XL",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.380",
      "Total_Line_Amount": "2.28",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X59330"
    },
    {
      "testfield1": "",
      "Sl_No": "0004",
      "Part_Number_SKU": "X63680",
      "Quantity": "1",
      "Item_Description": "FRSHIRT/CRHRT/EVIS/NVY/LS-0XLLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.700",
      "Total_Line_Amount": "0.70",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X63680"
    },
    {
      "testfield1": "",
      "Sl_No": "0004",
      "Part_Number_SKU": "X64302",
      "Quantity": "5",
      "Item_Description": "FR SHRT/7OZ 88C/12N/STRP/NVY-0XLLS",
      "Unit_Of_Measure": "",
      "Unit_Price": "0.630",
      "Total_Line_Amount": "3.15",
      "Sales_Tax_Percent": "",
      "Sales_Tax_Amount": "",
      "Freight_Surcharge_Amount": "",
      "Discount_Percent": "",
      "Discount_Amount": "",
      "Extended_Line_Amount": "",
      "PO_Number": "",
      "PO_Line_Item_Number": "",
      "Cost_Center": "",
      "Ship_From_Location": "",
      "field1": "",
      "Material": "X64302"
    }
  ]
};

// get the count
const count = data.line_items.length;

console.log("Total records:", count);
